spring:
  application:
    name: Spring Boot Karate Example

  datasource:
    driver-class-name: org.postgresql.Driver
    url: jdbc:postgresql://localhost:5432/
    username: postgres
    password: test

  jpa:
    hibernate:
      ddl-auto: update

logging:
  level:
    root: INFO

