spring:
  application:
    name: Spring Boot Karate Example

  datasource:
    driver-class-name: org.h2.Driver
    url: jdbc:h2:mem:db;
    username: sa
    password: sa

logging:
  level:
    root: INFO

